### ISSUE TITLE
Welcome to use the new architecture SDK

### ISSUE THREAD

**Issue by jiacfan** [Azure/azure-storage-file-go#10]
This is the new Azure storage File Go SDK based on new client architecture. Welcome to use it, and welcome any discussions on the design, implementation and new demands.

Thanks & Best Regards,
Jiachen

**Comment by DaveJKing** [comment]
Hi, I am using golag Mac OSX, go 10.3. I have followed normal procedures to add the package i.e
go get "github.com/Azure/azure-storage-file-go/2017-07-29/azfile" and then import "github.com/Azure/azure-storage-file-go/2017-07-29/azfile" in my go code.

import (
	"context"
	"fmt"
	"log"
	"net/url"
	"os"
)

func main() {

	// From the Azure portal, get your Storage account file service URL endpoint.
	accountName, accountKey := accountInfo()

	// Create a FileURL object to a file in the share (we assume the share & file already exist).
	u, _ := url.Parse(fmt.Sprintf("https://%s.file.core.windows.net/myshare/BigFile.bin", accountName))
	fileURL := NewFileURL(*u, NewPipeline(NewSharedKeyCredential(accountName, accountKey), PipelineOptions{}))

	file, err := os.Create("BigFile.bin") // Create the file to hold the downloaded file contents.
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	// Trigger parallel download with Parallelism set to 3, MaxRetryRequestsPerRange means the count of retry requests
	// could be sent if there is er ......

However, the import "github.com/Azure/azure-storage-file-go/2017-07-29/azfile"  line disappears and I get errors i.e undefined NewFileURL, NewPipeLine etc. Its as if is not seeing the azfile package. Please help. thanks you in advance.

**Comment by jiacfan** [comment]
Hey, @DaveJKing 

Thanks for providing feedback! 
Please add azfile before the NewFileURL and etc, as the methods are definied in azfile package. The zt_exmaples_tests.go is in the same package as "azfile", so it doesn't need to add azfile. suffix. We'll optimize the example further, and make it easy to be referenced.

In your case, please use code like:
`
// From the Azure portal, get your Storage account file service URL endpoint.
accountName, accountKey := accountInfo()

// Create a FileURL object to a file in the share (we assume the share & file already exist).
u, _ := url.Parse(fmt.Sprintf("https://%s.file.core.windows.net/myshare/BigFile.bin", accountName))
fileURL := azfile.NewFileURL(*u, azfile.NewPipeline(azfile.NewSharedKeyCredential(accountName, accountKey), azfile.PipelineOptions{}))

file, err := os.Create("BigFile.bin") // Create the file to hold the downloaded file contents.
if err != nil {
	log.Fatal(err)
}
defer file.Close()

// Trigger parallel download with Parallelism set to 3, MaxRetryRequestsPerRange means the count of retry requests
// could be sent if there is er ......
`

Best Regards,
Jiachen

**Comment by DaveJKing** [comment]
Hi Jiachen, my editor complains (Atom) but the code now works. It was the referencing that I found confusing . Thank you very much. Have a good day. Dave

**Comment by jiacfan** [comment]
Hi, @DaveJKing 

Welcome! And appreciate further suggestions.

Thanks,
Jiachen

**Comment by DaveJKing** [comment]
Hi a delete function would be very useful. Please excuse me if this already exists. I cannot see an example. Regards D.

**Comment by jiacfan** [comment]
Hi, @DaveJKing 

Here are [samples](https://github.com/Azure/azure-storage-file-go/blob/master/2017-07-29/azfile/zt_examples_test.go) for how to use FileURL, DirectoryURL and etc, and there is sample for Deleting. 

For example, for deleting file or share, please search following codes in the sample file:
```
        // Delete the file we created earlier.
	_, err = fileURL.Delete(ctx)
	if err != nil {
		log.Fatal(err)
	}

	// Delete the share we created earlier (with DeleteSnapshotsOptionNone as no snapshot exists and needs to be deleted).
	_, err = shareURL.Delete(ctx, DeleteSnapshotsOptionNone)
	if err != nil {
		log.Fatal(err)
	}
```

Thanks
Jiachen

**Comment by jiacfan** [comment]
Hi, @DaveJKing 

FYI, azure storage file SDK 0.3.0 has been released, it involves [sample optimizations](https://godoc.org/github.com/Azure/azure-storage-file-go/2017-07-29/azfile#pkg-examples), which solves the issue you mentioned, and helps to demonstrate how to use this SDK. 

Welcome try! And appreciate suggestions.

Thanks,
Jiachen
