### ISSUE TITLE
[bug] Could not get the metadata of snapshots

### ISSUE THREAD

**Issue by ZeroMagic** [Azure/azure-storage-file-go#25]
### Which version of the SDK was used?
v0.5.0

### Which platform are you using? (ex: Windows, Linux, Debian)
Linux

### What problem was encountered?
Firstly, I created a snapshot with metadata `initiator=snapshot-7f2660cc-2e71-410d-bc66-46bbcddd8304`. After creating successfully, I could saw the metadata in the portal.
![image](https://user-images.githubusercontent.com/12582312/64506298-a9e47980-d309-11e9-90e2-d6d10198bcc8.png)

Then, I used the function [`ListSharesSegment`](https://github.com/Azure/azure-storage-file-go/blob/master/azfile/zz_generated_service.go#L107) to get the snapshot. The metadata was nil. Following are the debugging logs in my program.
```
I0909 03:56:22.641583       1 controllerserver.go:390] Share(pvc-83fa5211-0e5a-4cf3-b03b-973eb02fea7c) snapshot(2019-09-09T03:56:22.0000000Z) Metadata: map[]
```

### How can we reproduce the problem in the simplest way?

1. Create a file share with a snapshot.
2. Use the function to get snapshot information.

### Have you found a mitigation/solution?

No.

/cc @andyzhangx

**Comment by zezha-msft** [comment]
Hi @ZeroMagic, thanks for reaching out!

Have you passed in the correct ListSharesOptions? Example [here](https://github.com/Azure/azure-storage-file-go/blob/master/azfile/zt_url_share_test.go#L606).

**Comment by ZeroMagic** [comment]
Awesome! It works after adding the `Metadata:  true` ListSharesOption.

Thanks! @zezha-msft
