### ISSUE TITLE
unhandled error caused panic

### ISSUE THREAD

**Issue by mowtschan** [Azure/azure-storage-file-go#27]
https://github.com/Azure/azure-storage-file-go/blob/825ad7914132416d8f2229b808b7cf399a644b2e/azfile/highlevel.go#L183

**Comment by zezha-msft** [comment]
Hi @mowtschan, thanks for reaching out!

Could you please elaborate on the error you got?

**Comment by mowtschan** [comment]
https://github.com/Azure/azure-storage-file-go/blob/825ad7914132416d8f2229b808b7cf399a644b2e/azfile/highlevel.go#L183-L184

Just assume the line 183 returns an error and `dr`is nil, then the line 184 will fail with:
`panic: runtime error: invalid memory address or nil pointer dereference`

**Comment by zezha-msft** [comment]
@mowtschan oh I see, that indeed looks like a bug, thank you so much for bringing this to our attention!
