### ISSUE TITLE
UploadFileToAzureFile missing headers.

### ISSUE THREAD

**Issue by edwinhayes** [Azure/azure-storage-file-go#33]
### Which version of the SDK was used?
0.6.0

### Which platform are you using? (ex: Windows, Linux, Debian)
Ubuntu Linux 18.04

### What problem was encountered?
Calling UploadFileToAzureFile() in the same manner as in the example (https://godoc.org/github.com/Azure/azure-storage-file-go/azfile#example-UploadFileToAzureFile), gets an error response indicating that some mandatory headers were missing:

```
azure-storage-file-go@v0.6.0/azfile/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=MissingRequiredHeader) =====
Description=An HTTP header that's mandatory for this request is not specified.
RequestId:7b298b92-501e-00c0-18eb-ed0033000000
Time:2020-02-28T03:58:06.6661551Z, Details: 
   Code: MissingRequiredHeader
   HeaderName: x-ms-blob-type
   PUT https://REDACTED.blob.core.windows.net/agent-file-transfer/new.file?timeout=61
   Authorization: REDACTED
   User-Agent: [Azure-Storage/0.6.0 (go1.13.8; linux)]
   X-Ms-Cache-Control: [no-transform]
   X-Ms-Client-Request-Id: [6c72d2d8-74f4-47dd-58ca-3bf4e985dd48]
   X-Ms-Content-Disposition: []
   X-Ms-Content-Encoding: []
   X-Ms-Content-Language: []
   X-Ms-Content-Length: [3135]
   X-Ms-Content-Type: []
   X-Ms-Date: [Fri, 28 Feb 2020 03:58:05 GMT]
   X-Ms-File-Attributes: [None]
   X-Ms-File-Creation-Time: [now]
   X-Ms-File-Last-Write-Time: [now]
   X-Ms-File-Permission: [inherit]
   X-Ms-Meta-Createdby: [REDACTED]
   X-Ms-Type: [file]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 An HTTP header that's mandatory for this request is not specified.
   Content-Length: [301]
   Content-Type: [application/xml]
   Date: [Fri, 28 Feb 2020 03:58:05 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [6c72d2d8-74f4-47dd-58ca-3bf4e985dd48]
   X-Ms-Error-Code: [MissingRequiredHeader]
   X-Ms-Request-Id: [7b298b92-501e-00c0-18eb-ed0033000000]
   X-Ms-Version: [2019-02-02]
```

### How can we reproduce the problem in the simplest way?
I haven't actually tried the literal example code, but I suspect it will fail as well.

### Have you found a mitigation/solution?
No.

**Comment by edwinhayes** [comment]
Cancel that, incompetence.  This is why embedded systems engineers shouldn't be allowed online...

**Comment by jbmcfarlin31** [comment]
Out of curiosity, what was the solution for this? I keep getting: `400 The value for one of the HTTP headers is not in the correct format.`

**Comment by edwinhayes** [comment]
Ah, from memory, because I didn't notice that Azure File storage and Azure Blob storage were different things with different APIs, so I was calling a File API function against a Blob URL, or something like that?

**Comment by jbmcfarlin31** [comment]
@edwinhayes do you by chance have some example code for working with blobls? I am trying to copy a file into a blob container.. perhaps the same thing you were trying to do.

**Comment by edwinhayes** [comment]
Not that's open sorry.  Working solution looks _basically_ like this though:
```
blobURL := azblob.NewBlockBlobURL(u, azblob.NewPipeline(creds, azblob.PipelineOptions{}))
_, err = azblob.UploadFileToBlockBlob(c, f, blobURL,azblob.UploadToBlockBlobOptions{})
```

**Comment by marvinbuss** [comment]
This can happen, when using the blob SDK and configuring the dfs endpoint of your storage account. Make sure you use the right SDK with the right endpoint. I have seen this happen when using "mystorage.dfs.core.windows.net" instead of "mystorage.blob.core.windows.net" in combination with the Azure Storage SDK. The dfs endpoint only works with the Azure data lake SDK.
