### ISSUE TITLE
UploadFileToAzureFile: The value of one of the HTTP headers is in the wrong format

### ISSUE THREAD

**Issue by jbmcfarlin31** [Azure/azure-storage-file-go#36]
### Which version of the SDK was used?
`v0.7.0`

### Which platform are you using? (ex: Windows, Linux, Debian)
`Linux - Ubuntu 16.04`

### What problem was encountered?
I was following the example set forth here: [UploadFileToAzureFile](https://godoc.org/github.com/Azure/azure-storage-file-go/azfile#example-UploadFileToAzureFile)

I was attempting to upload a file to a blob container using the same exact code. The only changes I made was the `https://%s.file.core.windows.net/myshare/BigFile.bin` became a URL to my blob container: `https://%s.blobl.my.domain.com/testcontainer/%s` where `%s` was "`storageAccountName`" and "`fileName`".

Upon running my program, I get the following returned:
 ```
2020/05/27 20:59:32 -> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /root/odev/pkg/mod/github.com/!azure/azure-storage-file-go@v0.7.0/azfile/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=) =====
Description=The value for one of the HTTP headers is not in the correct format.
RequestId:d049d666-8e3a-0c3a-6ffa-a9c151f89e08
Time:2020-05-27T20:59:50.6667928Z, Details:
   Code: InvalidHeaderValue
   HeaderName: x-ms-version
   HeaderValue: 2019-02-02
   PUT https://storageaccount.my.domain.name/testcontainer/README.md?timeout=61
   Authorization: REDACTED
   User-Agent: [Azure-Storage/0.7.0 (go1.13.10; linux)]
   X-Ms-Cache-Control: [no-transform]
   X-Ms-Client-Request-Id: [33d55b42-ad67-4364-7e59-26f5fe561775]
   X-Ms-Content-Disposition: []
   X-Ms-Content-Encoding: []
   X-Ms-Content-Language: []
   X-Ms-Content-Length: [114]
   X-Ms-Content-Type: []
   X-Ms-Date: [Wed, 27 May 2020 20:59:31 GMT]
   X-Ms-File-Attributes: [None]
   X-Ms-File-Creation-Time: [now]
   X-Ms-File-Last-Write-Time: [now]
   X-Ms-File-Permission: [inherit]
   X-Ms-Meta-Createdby: [REDACTED]
   X-Ms-Type: [file]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 The value for one of the HTTP headers is not in the correct format.
   Content-Length: [328]
   Content-Type: [application/xml]
   Date: [Wed, 27 May 2020 20:59:50 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Request-Id: [d049d666-8e3a-0c3a-6ffa-a9c151f89e08]
```

### How can we reproduce the problem in the simplest way?
Not sure, follow the same example as the link posted above and then change the url to that of a blob container?

### Have you found a mitigation/solution?
No, not yet.

**Comment by zezha-msft** [comment]
Hi @jbmcfarlin31, to upload to the blob service, you need to use the [azblob package](https://github.com/Azure/azure-storage-blob-go/tree/master/azblob) instead.
