### ISSUE TITLE
download file shows github.com/Azure/azure-storage-file-go/azfile.newStorageError

### ISSUE THREAD

**Issue by Scarlettliuyc** [Azure/azure-storage-file-go#43]
### Which version of the SDK was used?
From Storage Explorer Version: 1.15.1

### Which platform are you using? (ex: Windows, Linux, Debian)
Windows 10

### What problem was encountered?
when using Storage Explorer download files sometimes it shows error about path cannot found.
![image](https://user-images.githubusercontent.com/69622329/93548466-d6f64e00-f999-11ea-98c5-b372c73f4dfa.png)

the log have something about  azure-storage-file-go/azfile.newStorageError,
2020/09/14 23:44:43 WARN: Failed to check if the destination is a folder or a file (Azure Files). Assuming the destination is a file: -> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.8.0/azfile/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=ResourceNotFound) =====
Description=The specified resource does not exist.
RequestId:1f61c0a3-a01a-0070-72f1-8a75dc000000
Time:2020-09-14T23:44:42.9878564Z, Details: 
   Code: ResourceNotFound
   GET https://sanzplibrary.file.core.windows.net/downloads/Serials/1.contents/Vanuatu_Daily_Post_contents.htm?restype=directory&se=2020-10-14t23%3A44%3A39z&sig=-REDACTED-&sp=rl&sr=s&sv=2018-03-28&timeout=901
   User-Agent: [Microsoft Azure Storage Explorer, 1.14.2, win32,  AzCopy/10.5.0 Azure-Storage/0.8.0 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [4a984571-a79a-482b-718f-6051db5f48bc]
### How can we reproduce the problem in the simplest way?
it not happen every time, cannot reproduce it.

### Have you found a mitigation/solution?
When restart the Storage Explorer or restart PC it can work  

please also check for the log, you also can get reference from my github issue in Azure storage Explorer https://github.com/microsoft/AzureStorageExplorer/issues/3555 

[fa98b9dd-bf5f-1f49-5d08-6aeb34fe1778.log](https://github.com/Azure/azure-storage-file-go/files/5243005/fa98b9dd-bf5f-1f49-5d08-6aeb34fe1778.log)

**Comment by zezha-msft** [comment]
Hi @Scarlettliuyc, from the StgExp I see that this is being followed up with an ICM, so I'll close it for now. Thank you.
