### ISSUE TITLE
Question on creating connection

### ISSUE THREAD

**Issue by kwontae** [Azure/azure-storage-file-go#44]
### Which version of the SDK was used?
latest
### Which platform are you using? (ex: Windows, Linux, Debian)
Linux

###Question
So when I went through the examples in the go doc of [azfile](https://godoc.org/github.com/Azure/azure-storage-file-go/azfile#example-FileSASSignatureValues), I only see the SAS or anonymous cred options. Do I use the anonymous one to connect via connection string to the fileshare?

**Comment by zezha-msft** [comment]
Hi, connection string is just a format. It contains the necessary credential info. You can extract the information and initialize the share/dir/file URL structs the regular way.
