### ISSUE TITLE
Restore from File share snapshot

### ISSUE THREAD

**Issue by akankshakumari393** [Azure/azure-storage-file-go#65]
### Which version of the SDK was used?
latest (v0.8.0)

### Which platform are you using? (ex: Windows, Linux, Debian)
Linux

### What problem was encountered?
There is no way to create a new volume from a file share snapshot.

**Comment by zezha-msft** [comment]
Hi @akankshakumari393, could you please clarify how that relates to the SDK?

**Comment by akankshakumari393** [comment]
Hi @zezha-msft 
I am looking for a way to take snapshot of a Flle share and then use the same snapshot to restore in some file share. Now for this, I could find this function to take snapshot [https://pkg.go.dev/github.com/Azure/azure-storage-file-go/azfile#example-ShareURL.CreateSnapshot](https://pkg.go.dev/github.com/Azure/azure-storage-file-go/azfile#example-ShareURL.CreateSnapshot).

But I didn't find anything which would restore from the snapshot. Is this implemented?

**Comment by zezha-msft** [comment]
Hi @akankshakumari393, that's not a data-plane operation to the best of my knowledge. This repo is the data-plane SDK. 

The management plane SDK is here: https://github.com/Azure/azure-sdk-for-go/tree/main/services/storage/mgmt
